name: "Get Jira Issues"
description: "Get the Jira Issues from a Pull Request commit messages"
inputs:
  githubToken:
    description: 'Github Token'
    required: true
runs:
  using: 'node20'
  main: 'index.js'